### PR TITLE
Various improvements (options, server, re-using image)

### PR DESCRIPTION
**Pull request by udondan**
Great action! I had to do some changes to make it work for me.

Sorry for not committing separate PR's. Customized it until it worked for me. 😃 

- Added `pdfOptions` input, so user can forward custom optons.
- Replaced the custom written server with [serve-static](https://www.npmjs.com/package/serve-static). The original server only served a single HTML page. I needed support for relative files: CSS, JS and custom fonts.
- Replaced the custom base Docker image with [buildkite/puppeteer](https://hub.docker.com/r/buildkite/puppeteer/). This one seems maintained, popular and only is 286MB in size. I think yours was 479MB.
- Removed some code that did not make sense to me (e.g. `legacyOptions`).  Wasn't passed from main.js.
- Removed the `includeAssets()` function. That seemd very custom to a specific setup. Now with the new http server, serving all files in the root, css files included in the HTML document (print styles) can be used

Let me know if anything conflicts with your setup. I tested your example.html file and it renders nicely.

### CODE REVIEW

**Comment by fifsky** [comment]
Great change, Thank you

**Comment by udondan** [comment]
thanks for merging :)

**Comment by bjornamr** [comment]
@udondan 

How is it possible to use custom css & fonts? Do  you have an example of that?

**Comment by udondan** [comment]
@bjornamr There's actually nothing special about it. I just reference CSS files which contain font declarations.

I'm using it to render my personal vita, source is here: https://github.com/udondan/www.udondan.com It makes use of [Font Awesome](https://fontawesome.com/). Result can be seen here https://www.udondan.com/ - PDF can be downloaded by clicking the red button on the right side.

**Pull request merged**
